database_bl := "$STREAMS_DIR/examples/supersonic_sbli/database_bl.dat"

help recipe_or_flag='':
    python recipes/recipe_help.py {{recipe_or_flag}}

nv:
	mkdir -p $APPTAINER_TMPDIR

	rm -f nv.sandbox

	taskset -c 0-15 sudo apptainer build --sandbox \
		nv.sandbox \
		"docker://nvcr.io/nvidia/nvhpc:24.7-devel-cuda_multi-ubuntu22.04"	

base:
	mkdir -p $APPTAINER_TMPDIR

	rm -f base.sandbox 
	echo $APPTAINER_TMPDIR
	time taskset -c 0-15 sudo -E apptainer build --sandbox --nv base.sandbox base.apptainer
	sudo du -sh base.sandbox

build:
	rm -f streams.sif
	echo $APPTAINER_TMPDIR
	test -e libstreams*.so && rm libstreams*.so || true
	# f2py -m libstreamsMin -h ./libstreamsMin.pyf --overwrite-signature ${STREAMS_DIR}/src/min_api.F90
	# f2py -m libstreamsMod -h ./libstreamsMod.pyf --overwrite-signature ${STREAMS_DIR}/src/mod_api.F90
	# python3 patch_pyf.py
	time taskset -c 0-15 sudo -E apptainer build --nv streams.sif build.apptainer
	du -sh streams.sif



#streams_flow_type := "shock-boundary-layer"
streams_flow_type := "boundary-layer"

# build a config json file as input to the solver
streamspy_dir := "$STREAMS_DIR/streamspy"
results_dir := "$STREAMS_DIR/streamspy/output"
eval := "$STREAMS_DIR/streamspy/output/LB_GymData/evaluation.h5"
training := "$STREAMS_DIR/streamspy/output/LB_GymData/training.h5"
checkpoint := "$STREAMS_DIR/streamspy/output/LB_GymData/checkpoints"
checkpoint_tag := "best"


input_dir := "$STREAMS_DIR/streamspy/output/input"
dist_dir  := "$STREAMS_DIR/streamspy/output/distribute_save"


# build a config json file as input to the solver
config_output := "$STREAMS_DIR/streamspy/output/input.json"

config:
	# create output directory if it does not exist
	test -d {{results_dir}} || mkdir -p {{results_dir}}

	test -f ./streams.sif

	apptainer exec ./streams.sif /usr/local/bin/streams-utils \
		config-generator {{config_output}} {{streams_flow_type}} \
		--steps 160000 \
		--reynolds-number 250 \
		--mach-number 2.28 \
		--x-divisions 600 \
		--y-divisions 208 \
		--z-divisions 100 \
		--json \
		--x-length 27.0 \
		--y-length 6.0 \
		--z-length 3.8 \
		--rly-wr 2.5 \
		--mpi-x-split 4 \
		--span-average-io-steps 10 \
		--probe-io-steps 0 \
		--python-flowfield-steps 500 \
		--use-python \
		--nymax-wr 201 \
		--sensor-threshold 0.1 \
		--restart-flag 1 \
		--dtsave-restart 33.756 \
		--fixed-dt .0008439 \
		--shock-impingement 15.0 \
		--shock-angle 8.0 \
		learning-based ddpg \
		    --slot-start 200 \
		    --slot-end 249 \
		    --obs-type u \
		    --obs-points "(257,146)(305,76)(297,20)(304,106)(322,42)(268,23)(322,80)(1,20)(287,14)(409,20)(316,18)(305,91)(484,26)(305,31)(379,55)(283,63)(297,46)(344,18)(506,30)(313,68)(433,32)(391,16)(362,56)(460,39)(280,27)(312,84)(333,78)(294,84)(332,53)(303,8)(526,39)(330,20)(321,63)(294,68)(347,71)(253,18)(315,53)(354,100)(368,14)(293,99)(380,19)(578,30)(11,17)(446,36)(325,101)(291,42)(307,58)(547,22)(408,71)(186,16)(473,38)(339,98)(323,12)(283,83)(372,88)(309,96)(298,7)(503,72)(271,46)(302,63)(392,78)(594,28)(423,31)(292,7)" \
		    --obs-xstart 80 \
		    --obs-xend 95 \
		    --obs-ystart 1 \
		    --obs-yend 25 \
		    --actuation-interval 100 \
		    --lag-steps 10000 \
		    --sensor-actuator-delay \
		    --train-episodes 1 \
		    --training-output {{training}} \
		    --eval-episodes 1 \
		    --eval-max-steps 100 \
		    --eval-output {{eval}} \
		    --checkpoint-interval 1 \
		    --checkpoint-dir {{checkpoint}} \
		    --amplitude 1.0 \
		    --hidden-width 256 \
		    --learning-rate 0.0003 \
		    --gamma 0.99 \
		    --tau 0.005 \
		    --batch-size 64 \
		    --buffer-size 100000 \

	cat {{config_output}}

run:
    #!/usr/bin/env sh
    set -eu
    : "${STREAMS_DIR:?set STREAMS_DIR}"
    : "${STREAMS_UTILS_DIR:?set STREAMS_UTILS_DIR}"
    test -f $STREAMS_UTILS_DIR/streams.sif

    mkdir -p "{{input_dir}}" "{{dist_dir}}"

    cp {{config_output}} "{{input_dir}}/input.json"
    cp {{database_bl}} "{{input_dir}}/database_bl.dat"

    checkpoint_bind_arg=""
    if [ -d "{{checkpoint}}" ]; then checkpoint_bind_arg="--bind {{checkpoint}}:/checkpoints"; fi

    apptainer exec --nv \
        --bind "{{dist_dir}}:/distribute_save,{{input_dir}}:/input,$STREAMS_DIR/streamspy:/runtimesolver" \
        $checkpoint_bind_arg \
        $STREAMS_UTILS_DIR/streams.sif \
        /usr/local/bin/streams-utils run-container \

# ADDITIONAL RUN OPTIONS (LearningBased ONLY)
# To evaluate existing parameters: Append the --eval-only AND --checkpoint to the end of the run recipe (i.e. under /usr/local/...).
# To train w/o evaluation, starting without (or with) existing parameters: Append the --train-only (AND --checkpoint) to the end of the run recipe (i.e. under /usr/local/...). 
# Note: If --checkpoint isn't working, double check your path is correctly specified in checkpoint and checkpoint tag, found above the config recipe
#	  --eval-only \
#	  --train-only \
#	  --checkpoint "/checkpoints/{{checkpoint_tag}}"



#analysis:
#        apptainer exec --nv \
#                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input \
#                ./streams.sif \
#                python3 /streamspy/Analysis/analysis_main.py \
#                --results_dir {{results_dir}} \
#                --episode-tag ep_0000 \
#                --analysis-method DMD \

analysis:
        apptainer exec --nv \
                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input,{{streamspy_dir}}:/streamspy \
                ./streams.sif \
                python3 /streamspy/Analysis/analysis_main.py \
                --results_dir {{results_dir}} \
                --episode-tag ep_0000 \
                --analysis-method pysensors \
                --num-sensors 6
                
visualize:
        apptainer exec --nv \
                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input,{{streamspy_dir}}:/streamspy \
                ./streams.sif \
                python3 /streamspy/Visualize/visualize_main.py \
                 --results_dir {{results_dir}} \
                 --episode-tag ep_0000 \
                 --vis-type snapshot \
                 --snapshot-number 1 \
                 --variable rho \
                
#visualize:
#        apptainer exec --nv \
#                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input \
#                ./streams.sif \
#                python3 /streamspy/Visualize/visualize_main.py \
#                 --results_dir {{results_dir}} \
#                 --episode-tag ep_0000 \
#                 --vis-type animation \
#                 --variable w \

#visualize:
#        apptainer exec --nv \
#                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input \
#                ./streams.sif \
#                python3 /streamspy/Visualize/visualize_main.py \
#                --results_dir {{results_dir}} \
#                --episode-tag ep_0000 \
#                --vis-type rl_metrics

#visualize:
#        apptainer exec --nv \
#                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input \
#                ./streams.sif \
#                python3 /streamspy/Visualize/visualize_main.py \
#                --results_dir {{results_dir}} \
#                --episode-tag ep_0000 \
#                --vis-type sa_data \

model:
        apptainer exec --nv \
                --bind {{results_dir}}/distribute_save:/distribute_save,{{results_dir}}/input:/input \
                ./streams.sif \
                python3 /streamspy/Modeling/modeling_main.py \
                --results_dir {{results_dir}} \
                --episode-tag ep_0000 \
                --model-type dmdc \
                --energy 100 \
	
	
# get a shell inside the container
# requires the ./output directory (with its associated folders) to be created, 
# and a ./streams.sif file to be made
shell:
	apptainer shell --nv --bind ./output/distribute_save:/distribute_save,./output/input:/input ./streams.sif

# get a shell inside the container
# and bind your $STREAMS_DIR environment variable to the folder
# /streams
local:
	apptainer shell --nv --bind $STREAMS_DIR:/streams ./base.sif

vtk:
	cargo r --release -- hdf5-to-vtk ./output/distribute_save
